name: Retro Vibe Final
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg
          pip install -U requests
      - name: Run Bot
        env:
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
        run: python bot.py
