name: Retro 7 Reels Daily
on:
  schedule:
    - cron: '30 2 * * *'   # 8:00 AM IST
    - cron: '30 4 * * *'   # 10:00 AM
    - cron: '30 6 * * *'   # 11:30 AM
    - cron: '30 9 * * *'   # 2:30 PM
    - cron: '30 12 * * *'  # 6:00 PM
    - cron: '30 15 * * *'  # 8:30 PM
    - cron: '30 17 * * *'  # 11:00 PM
  workflow_dispatch:

jobs:
  reels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg
          pip install -U requests yt-dlp
      - name: Run Bot
        env:
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
        run: python shorts_bot.py
